FROM php:5.6-apache

RUN docker-php-ext-install mysqli

COPY ./entrypoint.sh /entrypoint.sh 

RUN chmod 777 /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

COPY ./wp-install /var/www/html

CMD ["apache2-foreground"]
EXPOSE 80

